version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  python-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development

volumes:
  mongo_data:

